[package]
name = "events"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
amqprs = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow ={ workspace = true }
log ={ workspace = true }
tokio ={ workspace = true }
async-trait = "0.1.77"